name: nutridish
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avocado_toast.jpg
    - assets/greek_yogurt.jpg
    - assets/avocado_salad.jpg
    - assets/egg_breakfast.jpg
    - assets/healthy_salad.jpg
    - assets/vegetable_stir_fry.jpg
    - assets/fluffy_pancakes.jpeg
    - assets/fruit_smoothie.jpeg
    - assets/logo.png
    - assets/profile_picture.jpg
